import { Russo_One } from "next/font/google";
import "./globals.css";
import Header8 from "@/components/headers/Header8";
import Footer2 from "@/components/footers/Footer2";

const layoutLinks = [
  { href: "#home", text: "Home" },
  { href: "#about", text: "About" },
  { href: "#services", text: "Services" },
  { href: "#portfolio", text: "Portfolio" },
  { href: "#blog", text: "Blog" },
  { href: "#contact", text: "Contact" },
];

const russoOne = Russo_One({
  weight: "400",
  variable: "--font-russo-one",
  subsets: ["latin"],
});

export const metadata = {
  title: "Trendsetter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={russoOne.variable}>
        <Header8 links={layoutLinks} />
        <main className="container">{children}</main>
        <Footer2 />
      </body>
    </html>
  );
}
